//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompanyMaster> CompanyMasters { get; set; }
        public DbSet<FormMaster> FormMasters { get; set; }
        public DbSet<ModuleMaster> ModuleMasters { get; set; }
        public DbSet<SubCompanyMaster> SubCompanyMasters { get; set; }
        public DbSet<UserFormTran> UserFormTrans { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
        public DbSet<UserModuleTran> UserModuleTrans { get; set; }
        public DbSet<AccountingYear> AccountingYears { get; set; }
        public DbSet<RoleMaster> RoleMasters { get; set; }
        public DbSet<TaxMaster> TaxMasters { get; set; }
        public DbSet<TaxTran> TaxTrans { get; set; }
    }
}
